// DeskScene — Generated by gltfjsx (D-06) and adapted for Phase 5 interactivity.
//
// Source model: see .planning/phases/05-gltf-integration-visual-polish/05-02-MODEL-NOTES.md
//   for URL, license, attribution, and node-name inventory.
//
// Architecture: visual meshes are separated from raycasting hit-areas.
//   - Non-interactive objects: plain <mesh> with GLTF-baked material.
//   - Interactive objects (monitor screen, phone stand, papers):
//       1. A non-raycasting <mesh> with a custom material (emissive glow managed by
//          hoveredObject store subscription via useEffect).
//       2. An invisible <InteractiveMesh> at the same position for raycasting, cursor,
//          panel routing, and cameraPreset — the test contract surface.
//   This separation ensures GLTF geometry is visible with correct lighting while the
//   InteractiveMesh abstraction (and its tests) remain unchanged.
//
// gltfjsx auto-generated header (preserved for provenance per D-06):
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/desk-draco.glb -t -r /3d-portfolio/ --output src/components/3d/DeskScene.tsx
// Author: Nyangire (https://sketchfab.com/Nyangire)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/low-poly-computer-desk-646ed84ecd9d40089c31d94f79334ca5
// Title: Low Poly Computer Desk

import { useRef, useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useStore } from '@/store/useStore'
import InteractiveMesh from '@/components/3d/InteractiveMesh'

// Mapping from semantic mesh role to actual GLB node name (D-05 code-mapping decision
// recorded in 05-02-MODEL-NOTES.md). Update this constant if the model is replaced.
const MESH_MAP = {
  monitorScreen: 'Computer_monitor001_ComputerDesk_0', // from MODEL-NOTES.md "projects" mapping
  aboutProp:     'Phone_stand_ComputerDesk_0',          // from MODEL-NOTES.md "about" mapping
  contactProp:   'Paper_ComputerDesk_0',                // from MODEL-NOTES.md "contact" mapping
  monitorBody:   'Cube000_ComputerDesk_0',              // monitor casing (non-interactive)
  desk:          'Office_desk_ComputerDesk_0',          // desk surface — GLTF-baked material
  lamp:          '',                                     // model has no dedicated lamp mesh
  floor:         '',                                     // model has no floor mesh
} as const

// gltfjsx-emitted GLTFResult interface — typed node inventory from the GLB.
// Note: gltfjsx converts node names: "Cube.000" → "Cube000", ".001" → "001".
type GLTFResult = GLTF & {
  nodes: {
    KeyboardCable_ComputerDesk_0: THREE.Mesh
    Paper2_ComputerDesk_0: THREE.Mesh
    Monitor_cable_ComputerDesk_0: THREE.Mesh
    Speakers_cable_ComputerDesk_0: THREE.Mesh
    Mouse_cord_ComputerDesk_0: THREE.Mesh
    CD_ComputerDesk_0: THREE.Mesh
    Drawers_ComputerDesk_0: THREE.Mesh
    Phone_stand_ComputerDesk_0: THREE.Mesh
    Phonehandle_ComputerDesk_0: THREE.Mesh
    CD_case_ComputerDesk_0: THREE.Mesh
    Pen_ComputerDesk_0: THREE.Mesh
    Paper_ComputerDesk_0: THREE.Mesh
    Floppy_disk_FloppyDisk_0: THREE.Mesh
    Keyboard_ComputerDesk_0: THREE.Mesh
    SpeakerR_ComputerDesk_0: THREE.Mesh
    SpeakerL_ComputerDesk_0: THREE.Mesh
    Mousepad_ComputerDesk_0: THREE.Mesh
    Mouse_ComputerDesk_0: THREE.Mesh
    Computer_case_ComputerDesk_0: THREE.Mesh
    Office_desk_ComputerDesk_0: THREE.Mesh
    Cube000_ComputerDesk_0: THREE.Mesh
    Computer_monitor001_ComputerDesk_0: THREE.Mesh
  }
  materials: {
    ComputerDesk: THREE.MeshStandardMaterial
    FloppyDisk: THREE.MeshStandardMaterial
  }
}

// Draco decoder must be configured at module scope, before any useGLTF call.
// Path is first-party static assets only — no untrusted URL injection (T-05-03-06).
useGLTF.setDecoderPath('/3d-portfolio/draco/')

// Preload at module scope — calling inside the component runs on mount, which is too late
// for Suspense to suspend before the first render (05-RESEARCH.md anti-pattern).
useGLTF.preload('/3d-portfolio/models/desk-draco.glb')

export default function DeskScene() {
  const { nodes, materials } = useGLTF('/3d-portfolio/models/desk-draco.glb') as GLTFResult
  const hoveredObject = useStore((s) => s.hoveredObject)

  // Refs for the emissive materials on interactive visual meshes.
  // Updated imperatively by the hoveredObject effect below — no re-render needed.
  const monitorMatRef = useRef<THREE.MeshStandardMaterial>(null)
  const phoneMatRef   = useRef<THREE.MeshStandardMaterial>(null)
  const paper1MatRef  = useRef<THREE.MeshStandardMaterial>(null)
  const paper2MatRef  = useRef<THREE.MeshStandardMaterial>(null)

  // Sync emissive intensity on the VISUAL meshes whenever hover state changes.
  // D-08: CRT screen idle = 0.45 (just above Bloom threshold 0.4 for ambient halo).
  // Phone stand and papers idle = 0 (no ambient glow — amber only on hover).
  useEffect(() => {
    const mon  = hoveredObject === 'monitor'
    const phone = hoveredObject === 'phone-stand'
    const pap  = hoveredObject === 'papers'
    if (monitorMatRef.current) monitorMatRef.current.emissiveIntensity = mon  ? 1.6  : 0.6
    if (phoneMatRef.current)   phoneMatRef.current.emissiveIntensity   = phone ? 1.2  : 0
    if (paper1MatRef.current)  paper1MatRef.current.emissiveIntensity  = pap  ? 1.5  : 0
    if (paper2MatRef.current)  paper2MatRef.current.emissiveIntensity  = pap  ? 1.5  : 0
  }, [hoveredObject])

  return (
    <group name="desk-scene" dispose={null} scale={0.02} position={[0, -1.5, 0]}>
      {/* Non-interactive desk surface — accept GLTF-baked material (D-09) */}
      {MESH_MAP.desk && nodes[MESH_MAP.desk] && (
        <mesh
          name="desk-surface"
          geometry={nodes[MESH_MAP.desk].geometry}
          material={materials.ComputerDesk}
          castShadow
          receiveShadow
          scale={0.271}
        />
      )}

      {/* Monitor body (casing) — non-interactive, GLTF-baked material */}
      {MESH_MAP.monitorBody && nodes[MESH_MAP.monitorBody] && (
        <mesh
          name="monitor-body"
          geometry={nodes[MESH_MAP.monitorBody].geometry}
          material={materials.ComputerDesk}
          position={[10.874, 0, 115.729]}
          rotation={[0, 0.58, 0]}
          scale={0.394}
          castShadow
          receiveShadow
        />
      )}

      {/* Static decorative meshes — GLTF-baked materials (D-09).
          Paper2 is rendered below in the interactive visual layer. */}
      <mesh geometry={nodes.KeyboardCable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} />
      <mesh geometry={nodes.Monitor_cable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-3.9, 74.815, 28.04]} />
      <mesh geometry={nodes.Speakers_cable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[27.417, 74.815, 27.427]} />
      <mesh geometry={nodes.Mouse_cord_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} />
      <mesh geometry={nodes.CD_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-76.997, 75.076, 57.333]} rotation={[-Math.PI, 1.261, -Math.PI]} scale={0.1} />
      <mesh geometry={nodes.Drawers_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[65.098, 0, 55.308]} />
      <mesh geometry={nodes.Phonehandle_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[46.949, 79.24, 18.508]} rotation={[0.167, -0.19, 0.032]} scale={0.263} />
      <mesh geometry={nodes.CD_case_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-76.997, 75.356, 57.333]} rotation={[-Math.PI, 1.261, -Math.PI]} scale={0.064} />
      <mesh geometry={nodes.Pen_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[76.512, 76.014, 45.557]} rotation={[0, 0.244, 0]} scale={0.005} />
      <mesh geometry={nodes.Floppy_disk_FloppyDisk_0.geometry} material={materials.FloppyDisk} position={[-41.906, 74.815, 65.87]} rotation={[Math.PI / 2, 0, 0.247]} />
      <mesh geometry={nodes.Keyboard_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-3.76, 74.815, 55.898]} scale={0.305} />
      <mesh geometry={nodes.SpeakerR_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-33.15, 74.815, 31.868]} rotation={[0, 0.446, 0]} scale={0.18} />
      <mesh geometry={nodes.SpeakerL_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[27.417, 74.815, 27.427]} rotation={[0, -0.102, 0]} scale={0.18} />
      <mesh geometry={nodes.Mousepad_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[42.964, 74.815, 54.261]} rotation={[0, -0.115, 0]} scale={0.149} />
      <mesh geometry={nodes.Mouse_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} scale={0.271} />
      <mesh geometry={nodes.Computer_case_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-55.078, 74.815, 31.19]} rotation={[0, 0.036, 0]} scale={0.229} />

      {/* ── Interactive visual layer ────────────────────────────────────────────
          These meshes are the VISIBLE objects. raycast={() => {}} disables hit
          detection so the transparent InteractiveMesh siblings handle all events.
          Emissive intensity is driven by the hoveredObject useEffect above.     */}

      {/* CRT monitor screen — phosphor green emissive. Dark base so the green
          glow reads as a CRT screen rather than a solid-colour fill.
          Idle emissiveIntensity 0.45 keeps Bloom alive at rest (threshold 0.4). */}
      <mesh
        geometry={nodes[MESH_MAP.monitorScreen].geometry}
        position={[-3.9, 74.815, 28.04]}
        scale={[0.192, 0.144, 0.096]}
        castShadow
        receiveShadow
        raycast={() => {}}
      >
        <meshStandardMaterial ref={monitorMatRef} color="#1a1a1a" emissive="#39ff14" emissiveIntensity={0.6} />
      </mesh>

      {/* Phone stand — off-white vintage-plastic base; amber glow on hover only. */}
      <mesh
        geometry={nodes[MESH_MAP.aboutProp].geometry}
        position={[50.705, 74.815, 18.869]}
        rotation={[0, -0.193, 0]}
        castShadow
        receiveShadow
        raycast={() => {}}
      >
        <meshStandardMaterial ref={phoneMatRef} color="#f0ede8" emissive="#ffb347" emissiveIntensity={0} />
      </mesh>

      {/* Paper 1 (Paper_ComputerDesk_0) — cream base; both papers glow together. */}
      <mesh
        geometry={nodes[MESH_MAP.contactProp].geometry}
        position={[74.855, 74.63, 39.723]}
        rotation={[0, 0.12, 0]}
        scale={0.1}
        castShadow
        receiveShadow
        raycast={() => {}}
      >
        <meshStandardMaterial ref={paper1MatRef} color="#f0ece0" emissive="#ffb347" emissiveIntensity={0} />
      </mesh>

      {/* Paper 2 (Paper2_ComputerDesk_0) — same cream + amber emissive as Paper 1
          so both sheets visually react together when "papers" is hovered. */}
      <mesh
        geometry={nodes.Paper2_ComputerDesk_0.geometry}
        position={[76.15, 75.001, 39.723]}
        rotation={[0, 0.031, 0]}
        scale={0.1}
        castShadow
        receiveShadow
        raycast={() => {}}
      >
        <meshStandardMaterial ref={paper2MatRef} color="#f0ece0" emissive="#ffb347" emissiveIntensity={0} />
      </mesh>

      {/* ── Interactive hit-area layer ──────────────────────────────────────────
          Transparent InteractiveMesh wrappers handle raycasting, cursor change,
          cameraPreset, and panel routing. The test contract (panelId / name props)
          lives here. opacity={0} + transparent makes them invisible; they still
          receive pointer events. The papers box covers both paper meshes.         */}

      <InteractiveMesh
        name="monitor"
        panelId="projects"
        position={[-3.9, 74.815, 28.04]}
        geometry={nodes[MESH_MAP.monitorScreen].geometry}
        scale={[0.192, 0.144, 0.096]}
        color="#000000"
        emissive="#000000"
        transparent
        opacity={0}
      />

      <InteractiveMesh
        name="phone-stand"
        panelId="about"
        position={[50.705, 74.815, 18.869]}
        geometry={nodes[MESH_MAP.aboutProp].geometry}
        rotation={[0, -0.193, 0]}
        color="#000000"
        emissive="#000000"
        transparent
        opacity={0}
      />

      {/* Papers hit area — single box that covers both Paper and Paper2 positions. */}
      <InteractiveMesh
        name="papers"
        panelId="contact"
        position={[75.5, 74.815, 39.723]}
        args={[15, 2, 15]}
        color="#000000"
        emissive="#000000"
        transparent
        opacity={0}
      />
    </group>
  )
}
