// DeskScene — Generated by gltfjsx (D-06) and adapted for Phase 5 interactivity.
//
// Source model: see .planning/phases/05-gltf-integration-visual-polish/05-02-MODEL-NOTES.md
//   for URL, license, attribution, and node-name inventory.
//
// Generation command (Plan 03 Task 1, Operation A):
//   npx --yes gltfjsx@^6.5.3 \
//     3d-portfolio/public/models/desk-draco.glb \
//     -t -r /3d-portfolio/ \
//     -o 3d-portfolio/src/components/3d/DeskScene.tsx
//
// Adaptations applied on top of the gltfjsx scaffold (Operation B):
//   1. setDecoderPath at module scope — Plan 01 Draco WASM lives at /3d-portfolio/draco/
//   2. MESH_MAP constant — semantic role to actual node name from MODEL-NOTES.md
//   3. Interactive mesh JSX (D-07) — InteractiveMesh wrappers with GLTF geometry positions;
//      handler logic follows InteractiveMesh.tsx patterns; D-08 runtime emissive override
//      on monitor screen (#39ff14, emissiveIntensity={0.6} idle, 1.6 on hover)
//   4. MESH_MAP-driven render replacing the gltfjsx default return
//
// gltfjsx auto-generated header (preserved for provenance per D-06):
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 public/models/desk-draco.glb -t -r /3d-portfolio/ --output src/components/3d/DeskScene.tsx
// Author: Nyangire (https://sketchfab.com/Nyangire)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/low-poly-computer-desk-646ed84ecd9d40089c31d94f79334ca5
// Title: Low Poly Computer Desk

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import InteractiveMesh from '@/components/3d/InteractiveMesh'

// Mapping from semantic mesh role to actual GLB node name (D-05 code-mapping decision
// recorded in 05-02-MODEL-NOTES.md). Update this constant if the model is replaced.
const MESH_MAP = {
  monitorScreen: 'Computer_monitor001_ComputerDesk_0', // from MODEL-NOTES.md "projects" mapping
  aboutProp:     'Phone_stand_ComputerDesk_0',          // from MODEL-NOTES.md "about" mapping
  contactProp:   'Paper_ComputerDesk_0',                // from MODEL-NOTES.md "contact" mapping
  monitorBody:   'Cube000_ComputerDesk_0',              // monitor casing (non-interactive)
  desk:          'Office_desk_ComputerDesk_0',          // desk surface — GLTF-baked material
  lamp:          '',                                     // model has no dedicated lamp mesh
  floor:         '',                                     // model has no floor mesh
} as const

// gltfjsx-emitted GLTFResult interface — typed node inventory from the GLB.
// Note: gltfjsx converts node names: "Cube.000" → "Cube000", ".001" → "001".
type GLTFResult = GLTF & {
  nodes: {
    KeyboardCable_ComputerDesk_0: THREE.Mesh
    Paper2_ComputerDesk_0: THREE.Mesh
    Monitor_cable_ComputerDesk_0: THREE.Mesh
    Speakers_cable_ComputerDesk_0: THREE.Mesh
    Mouse_cord_ComputerDesk_0: THREE.Mesh
    CD_ComputerDesk_0: THREE.Mesh
    Drawers_ComputerDesk_0: THREE.Mesh
    Phone_stand_ComputerDesk_0: THREE.Mesh
    Phonehandle_ComputerDesk_0: THREE.Mesh
    CD_case_ComputerDesk_0: THREE.Mesh
    Pen_ComputerDesk_0: THREE.Mesh
    Paper_ComputerDesk_0: THREE.Mesh
    Floppy_disk_FloppyDisk_0: THREE.Mesh
    Keyboard_ComputerDesk_0: THREE.Mesh
    SpeakerR_ComputerDesk_0: THREE.Mesh
    SpeakerL_ComputerDesk_0: THREE.Mesh
    Mousepad_ComputerDesk_0: THREE.Mesh
    Mouse_ComputerDesk_0: THREE.Mesh
    Computer_case_ComputerDesk_0: THREE.Mesh
    Office_desk_ComputerDesk_0: THREE.Mesh
    Cube000_ComputerDesk_0: THREE.Mesh
    Computer_monitor001_ComputerDesk_0: THREE.Mesh
  }
  materials: {
    ComputerDesk: THREE.MeshStandardMaterial
    FloppyDisk: THREE.MeshStandardMaterial
  }
}

// Draco decoder must be configured at module scope, before any useGLTF call.
// Path is first-party static assets only — no untrusted URL injection (T-05-03-06).
useGLTF.setDecoderPath('/3d-portfolio/draco/')

// Preload at module scope — calling inside the component runs on mount, which is too late
// for Suspense to suspend before the first render (05-RESEARCH.md anti-pattern).
useGLTF.preload('/3d-portfolio/models/desk-draco.glb')

export default function DeskScene() {
  const { nodes, materials } = useGLTF('/3d-portfolio/models/desk-draco.glb') as GLTFResult

  return (
    <group name="desk-scene" dispose={null}>
      {/* Non-interactive desk surface — accept GLTF-baked material (D-09) */}
      {MESH_MAP.desk && nodes[MESH_MAP.desk] && (
        <mesh
          name="desk-surface"
          geometry={nodes[MESH_MAP.desk].geometry}
          material={materials.ComputerDesk}
          castShadow
          receiveShadow
          scale={0.271}
        />
      )}

      {/* Monitor body (casing) — non-interactive, GLTF-baked material */}
      {MESH_MAP.monitorBody && nodes[MESH_MAP.monitorBody] && (
        <mesh
          name="monitor-body"
          geometry={nodes[MESH_MAP.monitorBody].geometry}
          material={materials.ComputerDesk}
          position={[10.874, 0, 115.729]}
          rotation={[0, 0.58, 0]}
          scale={0.394}
          castShadow
          receiveShadow
        />
      )}

      {/* Static decorative meshes — GLTF-baked materials (D-09) */}
      <mesh geometry={nodes.KeyboardCable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} />
      <mesh geometry={nodes.Paper2_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[76.15, 75.001, 39.723]} rotation={[0, 0.031, 0]} scale={0.1} />
      <mesh geometry={nodes.Monitor_cable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-3.9, 74.815, 28.04]} />
      <mesh geometry={nodes.Speakers_cable_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[27.417, 74.815, 27.427]} />
      <mesh geometry={nodes.Mouse_cord_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} />
      <mesh geometry={nodes.CD_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-76.997, 75.076, 57.333]} rotation={[-Math.PI, 1.261, -Math.PI]} scale={0.1} />
      <mesh geometry={nodes.Drawers_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[65.098, 0, 55.308]} />
      <mesh geometry={nodes.Phonehandle_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[46.949, 79.24, 18.508]} rotation={[0.167, -0.19, 0.032]} scale={0.263} />
      <mesh geometry={nodes.CD_case_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-76.997, 75.356, 57.333]} rotation={[-Math.PI, 1.261, -Math.PI]} scale={0.064} />
      <mesh geometry={nodes.Pen_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[76.512, 76.014, 45.557]} rotation={[0, 0.244, 0]} scale={0.005} />
      <mesh geometry={nodes.Floppy_disk_FloppyDisk_0.geometry} material={materials.FloppyDisk} position={[-41.906, 74.815, 65.87]} rotation={[Math.PI / 2, 0, 0.247]} />
      <mesh geometry={nodes.Keyboard_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-3.76, 74.815, 55.898]} scale={0.305} />
      <mesh geometry={nodes.SpeakerR_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-33.15, 74.815, 31.868]} rotation={[0, 0.446, 0]} scale={0.18} />
      <mesh geometry={nodes.SpeakerL_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[27.417, 74.815, 27.427]} rotation={[0, -0.102, 0]} scale={0.18} />
      <mesh geometry={nodes.Mousepad_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[42.964, 74.815, 54.261]} rotation={[0, -0.115, 0]} scale={0.149} />
      <mesh geometry={nodes.Mouse_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[34.329, 76.164, 56.062]} scale={0.271} />
      <mesh geometry={nodes.Computer_case_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[-55.078, 74.815, 31.19]} rotation={[0, 0.036, 0]} scale={0.229} />

      {/* Three interactive meshes — InteractiveMesh wrapper preserves Phase 3 handler
          patterns: direct ref mutation for emissive, useStore.getState() click guard,
          cursor reset on unmount (D-07). Geometry positions come from gltfjsx output.
          D-08: CRT monitor screen gets phosphor green emissive override. */}

      {/* CRT monitor screen — opens Projects panel
          D-08: emissive="#39ff14" (phosphor green), emissiveIntensity={0.6} idle, 1.6 hover
          These locked values come from 05-UI-SPEC.md §3D Material Overrides table. */}
      <InteractiveMesh
        name="monitor"
        panelId="projects"
        position={[-3.9, 74.815, 28.04]}
        args={[19.2, 14.4, 9.6]}
        color="#1a1a1a"
        emissive="#39ff14"
        emissiveIntensity={0.6}
        hoverEmissiveIntensity={1.6}
        castShadow
        receiveShadow
      />

      {/* Phone stand / cradle — opens About panel
          Amber emissive overlay (05-UI-SPEC.md); idle 0.0, hover 1.2 */}
      <InteractiveMesh
        name="phone-stand"
        panelId="about"
        position={[50.705, 74.815, 18.869]}
        args={[8, 6, 8]}
        color="#c8a96e"
        emissive="#ffb347"
        emissiveIntensity={0}
        hoverEmissiveIntensity={1.2}
        castShadow
        receiveShadow
      />

      {/* Paper sheet — opens Contact panel
          Amber emissive overlay (05-UI-SPEC.md); idle 0.0, hover 1.2 */}
      <InteractiveMesh
        name="papers"
        panelId="contact"
        position={[74.855, 74.63, 39.723]}
        args={[10, 0.5, 13]}
        color="#8b7355"
        emissive="#ffb347"
        emissiveIntensity={0}
        hoverEmissiveIntensity={1.2}
        castShadow
        receiveShadow
      />
    </group>
  )
}
